### PR TITLE
Feature/sprint2

### PR DESCRIPTION
**Pull request by Mirrorgo**

### CODE REVIEW

**Comment by Mirrorgo** [comment]
https://audit-visualizer-lwz.vercel.app/

**Review by ylimezhang — CHANGES_REQUESTED** [review]
Change Assertion title to Applied Assertion； Make the button as “Revert Assertion”.
Excellent work! love the way of cutting the branch(es) :)

**Comment by Mirrorgo** [comment]
> Change Assertion title to Applied Assertion； Make the button as “Revert Assertion”. Excellent work! love the way of cutting the branch(es) :)

done

**Review by ylimezhang — APPROVED** [review]
LGTM！

**Pull request merged**
